### ISSUE TITLE
Allow client to stream cram from htsget server

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/modo-api#25]
The compose deployment now includes a functional htsget server. We need to allow the client to stream CRAM data from it as if it was available locally.

**Objective:** update client to stream from htsget with pysam.

**Requirements:**
+ [x] can stream (anonymously, no authentication yet)
+ [x] api methods work identically for local and remote data

e.g. something along the lines of:
```python
local = MODO('data/ex')
local.stream_cram('cram/demo1') # stream from disk

remote = MODO('http://example.org/s3', bucket='demo')
remote.stream_cram('cram/demo1') # stream over http
```

**Comment by AssafSternberg** [comment]
1. Added a function to slice remote CRAM files, slice_remote_cram(), and either stream the data or write it to a local file depending on the user providing an output filename or not.

2. Added a class method to MODO, stream_cram, that based on the location of the MODO (checks if s3_endpoint exists or not), and based on an output filename provided or not, either streams the data or writes it to a local file.
