### ISSUE TITLE
Add support for BCF format

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/modo-api#36]
MODO now supports remote streaming of CRAM files. The test dataset of the genome center is mainly BCF files, therefore we need to implement the same feature for variant files.

**Requirements:**
* [x] Make sure we can BCF files
* [ ] metadata are stored in `/data`
* [x] files can be read locally
* [x] files can streamed
* [x] output accessible as a [pysam.VariantRecord](https://pysam.readthedocs.io/en/latest/api.html#pysam.VariantRecord)

**Comment by AssafSternberg** [comment]
stream_genomics already supports BCF files, both reading and writing to, 

- for remote files BCF can be sliced and saved locally as a BCF file.

- local files BCF files can be read and saved as BCF or VCF (.vcf or .vcf.gz) and VCF files can be sliced and saved as BCF files.
