### ISSUE TITLE
handle copying data files into archive

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/modo-api#7]
When creating a modo from a yaml file, we should define a clear behaviour to include external files.

**Proposal:**
* External files can be included in the yaml file (under `data_path`).
* We check for their existence at import time
* We copy them by default, or optionally refer to them (or the opposite)
* If copied, the actual MODO metadata will contained the new path inside the archive.

**Comment by almutlue** [comment]
This has consequences for `modo.file_utils.extract_metadata`:
`instance.data_path` is currently expected to be an absolute path. Adapt accordingly.
